/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class biz_novelinsight_hypercube_HypercubeDimReducer */

#ifndef _Included_biz_novelinsight_hypercube_HypercubeDimReducer
#define _Included_biz_novelinsight_hypercube_HypercubeDimReducer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    getUnreadMessages
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_getUnreadMessages
  (JNIEnv *, jobject);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    scanVSTFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_scanVSTFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    isScanningComputing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_isScanningComputing
  (JNIEnv *, jobject);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    stopScanning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_stopScanning
  (JNIEnv *, jobject);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    startCalculateVSTParameterReduction
 * Signature: (Ljava/lang/String;FZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_startCalculateVSTParameterReduction
  (JNIEnv *, jobject, jstring, jfloat, jboolean, jboolean);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    isParameterReductionComputing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_isParameterReductionComputing
  (JNIEnv *, jobject);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    stopCalculateVSTParameterReduction
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_stopCalculateVSTParameterReduction
  (JNIEnv *, jobject);

/*
 * Class:     biz_novelinsight_hypercube_HypercubeDimReducer
 * Method:    removeVSTParameterReductionFiles
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_biz_novelinsight_hypercube_HypercubeDimReducer_removeVSTParameterReductionFiles
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
